# default sources
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# valgrind source
tap "louisbrunner/valgrind"

## formulae
brew "coreutils"
brew "magic-wormhole"
brew "neofetch"
brew "louisbrunner/valgrind/valgrind", args: ["HEAD"]

## casks
cask "visual-studio-code"
