# sources
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "louisbrunner/valgrind" # valgrind

# valgrind: detect leaks (Mojave-comptatible version)
brew "louisbrunner/valgrind/valgrind", args: ["HEAD"]

# wormhole: send files and directories to other computers easily
brew "magic-wormhole"
